import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from "next/image";
import { Logo } from "~/assets";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>STOP APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between bg-neutral p-[30px]">
          <h1 className="title text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            STOP APP
          </h1>
          <Image src={Logo} alt="Logo Stop-APP" width={150} height={150}/>
          <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="btn btn-primary block bg-transparent w-[289px] outline-brand"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in With GitHub"}
      </button>
    </div>
  );
};
